apiVersion: v1
name: alpine
version: 0.1.0
description: A basic Alpine Linux pod deployment
home: https://github.com/mtmazurik/Helm
sources:
  - https://github.com/mtmazurik/Helm/tree/master/alpine
icon: https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png

