apiVersion: v1
kind: Pod
metadata:
  name: quarrelsome-lion-alpine
spec:
  restartPolicy: Never
  containers:
    - name: donothing 
      image: "alpine:latest"
      imagePullPolicy: IfNotPresent
      command: ["/bin/sleep", "9000"]
#
# this is a pared down list to install alpine (directly)
# with $  kubectl create -f createPod.yaml   so I can reverse engineer the core HELM needed statements
# for a simplified deployment.yaml that is part of a Chart
