apiversio.image.pullPolicy }}: v1
kind: pod 
metadata:
  name: {{ template "alpine.fullname" . }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.service }}
    app.kubernetes.io/instance: {{ .Release.name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: {{ .Chart.Name }}
    app.kubernetes.io/name: {{ template "alpine.name" .}}
  spec:
    restartpolicy: {{ .Values.restartPolicy }}
    containers:
      - name: alpinelodge
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagepullpolicy: {{ .Values.image.pullPolicy }}
        command: ["/bin/sleep", "9000"]
