apiVersion: v1
kind: Pod 
metadata:
  name: {{ template "alpine.fullname" . }}
  labels:
    app.kubernetes.io/version: {{ .Chart.appVersion }}
    helm.sh/chart: {{ .Chart.name }}
    app.kubernetes.io/name: {{ template "alpine.name" .}}
  spec:
    restartpolicy: {{ .Values.restartPolicy }}
    containers:
      - name: donothing
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagepullpolicy: {{ .Values.image.pullPolicy }}
        command: ["/bin/sleep", "9000"]
